# Generated by Django 4.0.4 on 2022-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mythical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_description', models.TextField()),
                ('second_description', models.TextField()),
                ('third_description', models.TextField()),
                ('first_image', models.ImageField(upload_to='mythicals_images')),
                ('second_image', models.ImageField(upload_to='mythicals_images')),
                ('third_image', models.ImageField(upload_to='mythicals_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
