# Generated by Django 4.0.4 on 2022-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mythical',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mythical',
            name='first_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mythical',
            name='second_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mythical',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='mythicals_images'),
        ),
        migrations.AlterField(
            model_name='mythical',
            name='third_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mythical',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='mythicals_images'),
        ),
    ]
